In [1]:
import numpy as np

In [8]:
np.random.rand(500,600)

array([[0.49923285, 0.37836618, 0.97151485, ..., 0.79285218, 0.78750108,
        0.68145826],
       [0.8348313 , 0.3186911 , 0.53928653, ..., 0.89912661, 0.01635015,
        0.10840615],
       [0.36412276, 0.891072  , 0.67148818, ..., 0.94968242, 0.44241947,
        0.77335331],
       ...,
       [0.18549767, 0.77251089, 0.91195747, ..., 0.25935385, 0.2727086 ,
        0.28912416],
       [0.56677739, 0.84080283, 0.73894699, ..., 0.35407319, 0.95382519,
        0.61247373],
       [0.84998543, 0.08963259, 0.71723272, ..., 0.30581103, 0.18277584,
        0.01103458]])

In [18]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.randint()

In [30]:
import numpy as np
#myarray = np.arange(101)
rmxyarray = np.random.randint(0,11,101)

In [32]:
print(rmxyarray)

[ 7  4  3  1  5  5 10  0  8 10  5  2  3 10  3  2  9  2  2  3  6  3  8  0
  7  6  1  7  0 10  8  8  1  6  9  2  6  9  8  3  0  1  0  4  4 10  6  8
  8  2  2  2  3  7  5  7  0  7  3 10  0  7  3  5  7  3  2  8  2  8  1  1
  1  5  2  8  3  0  3  0  4  3  7  7  6  2  0  0 10  2  5  6  5  5  5  2
  5  7 10 10  1]


In [47]:
np.linspace(0,10,101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])